8 frontend create mock data
sighupio/fury-ui pull request #16
Opened 2023-05-18 14:05 UTC by AndreaDellaValle

2023-05-24 12:22 UTC, Al-Pragliola reviewed
I would also add the schema generation and verify in the Makefile, .drone.yml

2023-05-24 18:39 UTC, Al-Pragliola requested changes

2023-05-24 18:39 UTC, Al-Pragliola commented on web-client/src/ConfigurationContext.tsx
> +        apiUrl: 'http://localhost:8080/api/v1', // TILT URL
This is the local backend URL, maybe we can take also this address from environment variables

2023-05-24 18:39 UTC, Al-Pragliola commented on web-client/src/__tests__/App.test.tsx
> +  // const fetchEl = await screen.findByTestId('fetch-text')
let's remove commented code

2023-05-24 18:39 UTC, Al-Pragliola commented on web-client/sample-schema.yml
> +openapi: "3.0.0"
is this still needed?

2023-05-24 18:39 UTC, Al-Pragliola commented on web-client/README.md
> +### Local development with TILT
mm not really with TILT

2023-05-31 09:43 UTC, omissis approved these changes
SBAM

2023-05-31 15:04 UTC, Al-Pragliola approved these changes
LGTM

2023-05-31 15:05 UTC, merged