feat: added helm charts + dev env
sighupio/fury-ui pull request #17
Opened 2023-05-19 17:18 UTC by Al-Pragliola

2023-05-23 08:40 UTC, omissis requested changes

2023-05-23 08:40 UTC, omissis commented on .drone.yml
> +  - name: unit-test
nitpick
```suggestion
      - go mod download

  - name: unit-test
```

2023-05-23 08:40 UTC, omissis commented on .drone.yml
> +    image: golang:1.20
maybe we could use `quay.io/sighup/golang:1.20.4` if it included `goreleaser` as well?

2023-05-23 08:40 UTC, omissis commented on .gitignore
> +.kubeconfig
not sure why we started using `.kubeconfig` instead of `kubeconfig`?

2023-05-23 08:40 UTC, omissis commented on development/down.sh
add a `docker stop fury-ui-kind-registry`, either at line 11, or add an else (if force == 1 then remove else stop)

2023-05-23 08:40 UTC, omissis commented on Tiltfile
> +    link("https://fury-ui.dev/", "fury-ui-backend"),
perhaps it should point at the api endpoint, or to a swagger ui?
```suggestion
    link("https://fury-ui.dev/api/v1", "fury-ui-backend"),
```

2023-05-23 08:40 UTC, omissis commented on helm_chart/Chart.yaml
> +appVersion: 0.0.1
If I remember correctly, semver requires to start at `v0.1.0`

2023-05-23 08:40 UTC, omissis commented on helm_chart/charts/fury-ui-backend/Chart.yaml
> +appVersion: 0.0.1
If I remember correctly, semver requires to start at `v0.1.0`

2023-05-23 08:40 UTC, omissis commented on helm_chart/charts/fury-ui-backend/values.yaml
> +  tag: "0.0.1"
```suggestion
  tag: "0.1.0"
```

2023-05-23 08:40 UTC, omissis commented on helm_chart/charts/fury-ui-frontend/values.yaml
> +  tag: "0.0.1"
```suggestion
  tag: "0.1.0"
```

2023-05-23 08:40 UTC, omissis commented on helm_chart/charts/fury-ui-frontend/values.yaml
> +  apiUrl: "http://example.com/api/v1"
```suggestion
  apiUrl: "http://fury.dev/api/v1"
```

2023-05-23 08:40 UTC, omissis commented on web-client/src/logo.svg
can you make the logo bigger? 😬 `</troll>`

2023-05-23 08:40 UTC, omissis commented on development/up.sh
`mv development/up.sh scripts/dev-up.sh`

2023-05-23 08:40 UTC, omissis commented on development/utils.sh
`mv development/utils.sh scripts/dev-utils.sh`

2023-05-23 08:40 UTC, omissis commented on development/utils.sh
remember to update the references to utils.sh

2023-05-23 08:40 UTC, omissis commented on development/down.sh
`mv development/down.sh scripts/dev-down.sh`

2023-05-23 08:40 UTC, omissis commented on development/down.sh
development isn't a go standard layout folder, so I would skip it

2023-05-23 08:40 UTC, omissis commented on development/helm/ingress-nginx.yaml
`mv development/helm/ingress-nginx.yaml scripts/helm-values/ingress-nginx.yaml`

2023-05-23 08:40 UTC, omissis commented on development/helm/values.yaml
`mv development/helm/values.yaml development/helm-values/fury-ui.yaml`

2023-05-23 08:40 UTC, omissis commented on development/manifests/ctlptl-registry.yml
`mv development/manifests/ctlptl-registry.yml scripts/kubernetes-manifests/ctlptl-registry.yml`

2023-05-23 08:40 UTC, omissis commented on development/manifests/kind-config.yml
`mv development/manifests/kind-config.yml scripts/kubernetes-manifests/kind-config.yml`

2023-05-23 08:40 UTC, omissis commented on development/tiltfiles/ingress-nginx.tiltfile
`mv development/tiltfiles/ingress-nginx.tiltfile configs/tiltfiles/ingress-nginx.tiltfile`

2023-05-23 08:40 UTC, omissis commented on development/tiltfiles/setup.tiltfile
`mv development/tiltfiles/setup.tiltfile configs/tiltfiles/setup.tiltfile`

2023-05-24 14:04 UTC, omissis requested changes

2023-05-24 14:04 UTC, omissis commented on scripts/dev-down.sh
> +#!/usr/bin/env bash
```suggestion
#!/bin/sh -x
```

2023-05-24 14:04 UTC, omissis commented on scripts/dev-up.sh
> +#!/usr/bin/env bash
```suggestion
#!/bin/sh -x
```

2023-05-24 17:02 UTC, Al-Pragliola commented on helm_chart/values.yaml
> +    - host: fury-ui.domain.com
This file is for public usage, not for tilt, isn't it more helpful to keep a generic domain?

2023-05-25 12:02 UTC, omissis approved these changes

2023-05-25 12:22 UTC, merged